### ISSUE TITLE
[ADD] - Multiprocessing w/ spark to LIEMapper

### ISSUE THREAD

**Issue by ellioth** [ellioth/LIEMapperMultiprocessing#2]
# Summary
We need to use the spark tool to parallelized the mapping of the code. 

## Motivation
Not only as a requirement for the design project course, but also to 
improve the speed of mapping when we are dealing with multiple 
inputs.

## Expected
The spark tool will be used for the parallelized the mapping 
without interfering the insides of the kernel.

## Tasks
- [x] how to use the tool(simple example)
- [x] merge the tool with the mapping kernel.
- [x] test the tool with a single input.
- [x] test the tool with a 'N' inputs.
- [x] organized the 'N' outputs.
- [x] internal documentation.

## Additional context
Nothing to add
